/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FeatureCard: typeof import('./src/components/FeatureCard.vue')['default']
    FeatureCardRow: typeof import('./src/components/FeatureCardRow.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PasswordReset: typeof import('./src/components/PasswordReset.vue')['default']
    PasswordResetEmail: typeof import('./src/components/PasswordResetEmail.vue')['default']
    Protected: typeof import('./src/components/Protected.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signup: typeof import('./src/components/Signup.vue')['default']
    SignupCodeVerification: typeof import('./src/components/SignupCodeVerification.vue')['default']
    SignUpCodeVerification: typeof import('./src/components/SignUpCodeVerification.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    Testing: typeof import('./src/components/Testing.vue')['default']
  }
}
